### ISSUE TITLE
Обновить сообщение, возникающее при валидации неправильного пароля

### ISSUE THREAD

**Issue by maxbarsukov** [Followy-Dev/API-BugTracker#3]
**Опишите возникший баг**
Текущее сообщение невозможно правильно истолковать. Так, пароль не проходит валидацию при отсутствии заглавной буквы и т.д.

**Ожидаемое поведение**
Например, `Password must be at least 6 characters, including a number, an uppercase letter, and a lowercase letter`

**Comment by mazzz3r** [comment]
closed
